<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVe6ayjc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVe6ayjc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVe6ayjc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVe6ayjc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVe6ayjc\appProdProjectContainer([
    'container.build_hash' => 'Ve6ayjc',
    'container.build_id' => 'ebb5f085',
    'container.build_time' => 1701009611,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVe6ayjc');
