<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZj8p43g\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZj8p43g/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZj8p43g.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZj8p43g\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZj8p43g\appProdProjectContainer([
    'container.build_hash' => 'Zj8p43g',
    'container.build_id' => '810f43cf',
    'container.build_time' => 1699470164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZj8p43g');
