<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8wqlsxl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8wqlsxl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8wqlsxl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8wqlsxl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8wqlsxl\appDevDebugProjectContainer([
    'container.build_hash' => '8wqlsxl',
    'container.build_id' => '09bc6b90',
    'container.build_time' => 1701008190,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8wqlsxl');
