<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIe6nxbw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIe6nxbw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIe6nxbw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIe6nxbw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIe6nxbw\appDevDebugProjectContainer([
    'container.build_hash' => 'Ie6nxbw',
    'container.build_id' => '9e3d9e2d',
    'container.build_time' => 1699979751,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIe6nxbw');
